class LifeStyle:
  pets = [  
    "Dog",
    "Cat",
    "Reptile",
    "Amphibian",
    "Bird",
    "Fish",
    "Don't have but love",
    "Other",
    "Turtle",
    "Hamster",
    "Rabbit",
    "Pet-free",
    "All the pets",
    "Want a pet",
    "Allergic to pets",
  ]

  drinking = [
    "Not for me",
    "Sober",
    "Sober curious",
    "On special occasions",
    "Socially on weekends",
    "Most Nights",
  ]

  smoking = [
    "Social smoker",
    "Smoker when drinking",
    "Non-smoker",
    "Smoker",
    "Trying to quit",
  ]

  cannabis = [
    "Yes",
    "Occasionally",
    "Socially",
    "Never",
  ]

  workout = [
    "Everyday",
    "Often",
    "Sometimes",
    "Never",
  ]

  diet = [
    "Vegan",
    "Vegetarian",
    "Pescatarian",
    "Kosher",
    "Halal",
    "Carnivore",
    "Omnivore",
    "Other",
  ]

  social = [
    "Influencer status",
    "Socially active",
    "Off the grid",
    "Passive scroller",
  ]

  sleep = [
    "Early bird",
    "Night owl",
    "In a spectrum",
  ]
  all_data = [pets,drinking,smoking,cannabis,workout,diet,social,sleep]

class Basics:
  zodiac = [
    "Capricorn",
    "Aquarius",
    "Pisces",
    "Aries",
    "Taurus",
    "Gemini",
    "Cancer",
    "Leo",
    "Virgo",
    "Libra",
    "Scorpio",
    "Sagittarius",
  ]

  education = [
    "Bachelors",
    "In College",
    "High School",
    "PhD",
    "In Grad School",
    "Masters",
    "Trade School",
  ]

  children = [
    "I want children",
    "I don't want children",
    "I have children and want more",
    "I have children and don't want more",
    "Not sure yet",
  ]

  vaccinated = [
    "Vaccinated",
    "Unvaccinated",
    "Prefer not to say",
  ]

  personality = [
    "INTJ",
    "INTP",
    "ENTJ",
    "ENTP",
    "INFJ",
    "INFP",
    "ENFJ",
    "ENFP",
    "ISTJ",
    "ISFJ",
    "ESTJ",
    "ESFJ",
    "ISTP",
    "ISFP",
    "ESTP",
    "ESFP",
  ]

  communication = [
    "I stay on WhatsApp all day",
    "Big time texter",
    "Phone caller",
    "Video chatter",
    "I'm slow to answer on WhatsApp",
    "Bad texter",
    "Better in person",
  ]

  love_gesture = [

    "Thoughtful gestures",
    "Presents",
    "Touch",
    "Compliments",
    "Time together",
  ]
  all_data = [zodiac,education,children,vaccinated,personality,communication,love_gesture,]


class RelationshipType:
  relationship_type = [
    "Monogamy",
    "Ethical non-monogamy",
    "Open relationship",
    "Polyamory",
    "Open to exploring",
  ]

class Passions:
  passions = [
    "90s Kid",
    "Harry Potter",
    "SoundCloud",
    "Spa",
    "Self Care",
    "Heavy Metal",
    "House Parties",
    "Gin tonic",
    "Gymnastics",
    "Ludo",
    "Maggi",
    "Hot Yoga",
    "Biryani",
    "Meditation",
    "Sushi",
    "Spotify",
    "Hockey",
    "Basketball",
    "Slam Poetry",
    "Home Workout",
    "Theater",
    "Cafe hopping",
    "Sneakers",
    "Aquarium",
    "Instagram",
    "Hot Springs",
    "Walking",
    "Running",
    "Travel",
    "Language Exchange",
    "Movies",
    "Guitarists",
    "Social Development",
    "Gym",
    "Social Media",
    "Hip Hop",
    "Skincare",
    "J-Pop",
    "Cricket",
    "Shisha",
    "Freelance",
    "K-Pop",
    "Skateboarding",
    "Gospel",
    "Potterhead",
    "Trying New Things",
    "Photography",
    "Bollywood",
    "Bhangra",
    "Reading",
    "Singing",
    "Sports",
    "Poetry",
    "Stand up Comedy",
    "Coffee",
    "Karaoke",
    "Fortnite",
    "Free Diving",
    "Self Development",
    "Mental Health Awareness",
    "Foodie Tour",
    "Voter Rights",
    "Jiu-jitsu",
    "Climate Change",
    "Exhibition",
    "Walking My Dog",
    "LGBTQIA+ Rights",
    "Feminism",
    "VR Room",
    "Escape Cafe",
    "Shopping",
    "Brunch",
    "Investment",
    "Jetski",
    "Reggaeton",
    "Second-hand apparel",
    "Black Lives Matter",
    "Jogging",
    "Road Trips",
    "Vintage fashion",
    "Voguing",
    "Couchsurfing",
    "Happy hour",
    "Inclusivity",
    "Country Music",
    "Football",
    "Inline Skate",
    "Investing",
    "Tennis",
    "Ice Cream",
    "Ice Skating",
    "Human Rights",
    "Expositions",
    "Pig Roast",
    "Skiing",
    "Canoeing",
    "West End Musicals",
    "Snowboarding",
    "Pilates",
    "Pentathlon",
    "Broadway",
    "PlayStation",
    "Cheerleading",
    "Choir",
    "Pole Dancing",
    "Five-a-side Football",
    "Car Racing",
    "Pinterest",
    "Festivals",
    "Pub Quiz",
    "Catan",
    "Cosplay",
    "Motor Sports",
    "Coffee Stall",
    "Content Creation",
    "E-Sports",
    "Bicycle Racing",
    "Binge-Watching TV shows",
    "Songwriter",
    "Bodycombat",
    "Tattoos",
    "Painting",
    "Bodyjam",
    "Paddle Boarding",
    "Padel",
    "Blackpink",
    "Surfing",
    "Bowling",
    "Grime",
    "90s Britpop",
    "Bodypump",
    "Beach Bars",
    "Bodystep",
    "Paragliding",
    "Upcycling",
    "Equality",
    "Astrology",
    "Motorcycles",
    "Equestrian",
    "Entrepreneurship",
    "Sake",
    "BTS",
    "Cooking",
    "Environmental Protection",
    "Fencing",
    "Soccer",
    "Saxophonist",
    "Sci-Fi",
    "Dancing",
    "Film Festival",
    "Freeletics",
    "Gardening",
    "Amateur Cook",
    "Exchange Program",
    "Sauna",
    "Art",
    "Politics",
    "Flamenco",
    "Museum",
    "Activism",
    "DAOs",
    "Real Estate",
    "Podcasts",
    "Disability Rights",
    "Rave",
    "Pimms",
    "Drive Thru Cinema",
    "Rock Climbing",
    "BBQ",
    "Craft Beer",
    "Iced Tea",
    "Drummer",
    "Tea",
    "Board Games",
    "Roblox",
    "Pubs",
    "Rock",
    "Tango",
    "Drawing",
    "Trivia",
    "Pho",
    "Volunteering",
    "Environmentalism",
    "Rollerskating",
    "Wine",
    "Dungeons & Dragons",
    "Vlogging",
    "Electronic Music",
    "Ramen",
    "Weightlifting",
    "Live Music",
    "Writing",
    "Xbox",
    "World Peace",
    "Wrestling",
    "Literature",
    "Manga",
    "Pride",
    "Marathon",
    "Makeup",
    "Youth Empowerment",
    "YouTube",
    "Martial Arts",
    "Marvel",
    "Vegan Cooking",
    "Vermut",
    "Korean Food",
    "Twitter",
    "Volleyball",
    "Walking Tour",
    "Vinyasa",
    "Virtual Reality",
    "League of Legends",
    "NFTs",
    "Bar Hopping",
    "Nintendo",
    "Baseball",
    "Parties",
    "Ballet",
    "Band",
    "Online Games",
    "Battle Ground",
    "Beach Tennis",
    "Nightlife",
    "Online Shopping",
    "Sailing",
    "Olympic Gymnastics",
    "Bassist",
    "Online Broker",
    "Military",
    "Memes",
    "Among Us",
    "Motorbike Racing",
    "Motorcycling",
    "Metaverse",
    "Mindfulness",
    "Acapella",
    "Musical Instrument",
    "Art galleries",
    "Musical Writing",
    "Hiking",
    "Artistic Gymnastics",
    "Mountains",
    "Archery",
    "Atari",
    "Backpacking",
    "Fishing",
    "Clubbing",
    "Street Food",
    "Crossfit",
    "Concerts",
    "Climbing",
    "Baking",
    "Camping",
    "Blogging",
    "Collecting",
    "Cars",
    "Start ups",
    "Boba tea",
    "High School Sports",
    "Badminton",
    "Active Lifestyle",
    "Fashion",
    "Anime",
    "NBA",
    "MLB",
    "Funk music",
    "Caipirinha",
    "Indoor Activities",
    "Tempeh",
    "DIY",
    "Town Festivities",
    "Cycling",
    "Outdoors",
    "TikTok",
    "Picnicking",
    "Twitch",
    "Comedy",
    "Trap Music",
    "Music",
    "Triathlon",
    "Netflix",
    "Disney",
    "Rugby",
    "Açaí",
    "Samba",
    "Tarot",
    "Stock Exchange",
    "Stocks",
    "Swimming",
    "Table Tennis",
    "Killing time",
    "Working out",
    "Yoga",
    "Horror Movies",
    "Boxing",
    "Bar Chilling",
  ]